Class {
	#name : #FASTPWBModel,
	#superclass : #MooseModel,
	#category : #'FAST-PowerBuilder-Entities-Model'
}

{ #category : #accessing }
FASTPWBModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' #'FAST-Core-Model')
]

{ #category : #meta }
FASTPWBModel class >> annotation [
	<FMClass: #FASTPWBModel super: #MooseModel>
	<package: #'FAST-PowerBuilder-Entities'>
	<generated>
]
