Class {
	#name : #FamixPWBSourceTextAnchor,
	#superclass : #FamixPWBSourceAnchor,
	#traits : 'FamixTWithImmediateSource',
	#classTraits : 'FamixTWithImmediateSource classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBSourceTextAnchor class >> annotation [

	<MSEClass: #SourceTextAnchor super: #FamixPWBSourceAnchor>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBSourceTextAnchor class >> generatedSlotNames [
	<generated>
	'FamixPWBSourceTextAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBSourceTextAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTWithImmediateSource)
]

{ #category : #meta }
FamixPWBSourceTextAnchor class >> requirements [

	<generated>
	^ {  }
]
