Class {
	#name : #FamixPWBSourceLanguage,
	#superclass : #FamixPWBEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBSourceLanguage class >> annotation [

	<MSEClass: #SourceLanguage super: #FamixPWBEntity>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBSourceLanguage class >> generatedSlotNames [
	<generated>
	'FamixPWBSourceLanguage class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #(FamixTSourceLanguage)
]

{ #category : #meta }
FamixPWBSourceLanguage class >> requirements [

	<generated>
	^ {  }
]
