Class {
	#name : #FamixPWBAbstractFileAnchor,
	#superclass : #FamixPWBSourceAnchor,
	#traits : 'FamixTFileAnchor',
	#classTraits : 'FamixTFileAnchor classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBAbstractFileAnchor class >> annotation [

	<FMClass: #AbstractFileAnchor super: #FamixPWBSourceAnchor>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]
