Class {
	#name : #FamixPWBIndexedFileAnchor,
	#superclass : #FamixPWBAbstractFileAnchor,
	#traits : 'FamixTIndexedFileNavigation',
	#classTraits : 'FamixTIndexedFileNavigation classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBIndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #FamixPWBAbstractFileAnchor>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]
