Class {
	#name : #FamixPWBMultipleFileAnchor,
	#superclass : #FamixPWBSourceAnchor,
	#traits : 'FamixTMultipleFileAnchor',
	#classTraits : 'FamixTMultipleFileAnchor classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBMultipleFileAnchor class >> annotation [

	<FMClass: #MultipleFileAnchor super: #FamixPWBSourceAnchor>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]
