Class {
	#name : #FamixThisAccessNullObject,
	#superclass : #Object,
	#category : #'Famix-PowerBuilder-Entities-NullObject'
}

{ #category : #null }
FamixThisAccessNullObject >> from: aFamixPWBEvent [ 
	
]

{ #category : #null }
FamixThisAccessNullObject >> isWrite: aBoolean [
]

{ #category : #null }
FamixThisAccessNullObject >> mooseModel: aMooseModel [ 
	
]

{ #category : #null }
FamixThisAccessNullObject >> to: aFamixPWBUserObject [
	
]
