Class {
	#name : #FamixPWBFunctionFile,
	#superclass : #FamixPWBmajorObject,
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBFunctionFile class >> annotation [

	<MSEClass: #FunctionFile super: #FamixPWBmajorObject>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBFunctionFile class >> generatedSlotNames [
	<generated>
	'FamixPWBFunctionFile class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBFunctionFile class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FamixPWBFunctionFile class >> requirements [

	<generated>
	^ {  }
]
