Class {
	#name : #FamixPWBSqlQuery,
	#superclass : #MooseEntity,
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBSqlQuery class >> annotation [

	<FMClass: #SqlQuery super: #MooseEntity>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #meta }
FamixPWBSqlQuery class >> metamodel [

	<generated>
	^ FamixPWBModel metamodel
]

{ #category : #testing }
FamixPWBSqlQuery >> isAccess [

	<generated>
	^ false
]

{ #category : #testing }
FamixPWBSqlQuery >> isAssociation [

	<generated>
	^ false
]

{ #category : #testing }
FamixPWBSqlQuery >> isAttribute [

	<generated>
	^ false
]

{ #category : #testing }
FamixPWBSqlQuery >> isFunction [

	<generated>
	^ false
]

{ #category : #testing }
FamixPWBSqlQuery >> isInvocation [

	<generated>
	^ false
]

{ #category : #testing }
FamixPWBSqlQuery >> isMethod [

	<generated>
	^ false
]

{ #category : #testing }
FamixPWBSqlQuery >> isReference [

	<generated>
	^ false
]

{ #category : #testing }
FamixPWBSqlQuery >> isStructuralEntity [

	<generated>
	^ false
]

{ #category : #testing }
FamixPWBSqlQuery >> isType [

	<generated>
	^ false
]
