Class {
	#name : #FamixPWBCustomType,
	#superclass : #FamixPWBAbstractType,
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBCustomType class >> annotation [

	<MSEClass: #CustomType super: #FamixPWBAbstractType>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBCustomType class >> generatedSlotNames [
	<generated>
	'FamixPWBCustomType class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBCustomType class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FamixPWBCustomType class >> requirements [

	<generated>
	^ {  }
]
