Class {
	#name : #FamixPWBQueryFile,
	#superclass : #FamixPWBmajorObject,
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBQueryFile class >> annotation [

	<MSEClass: #QueryFile super: #FamixPWBmajorObject>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBQueryFile class >> generatedSlotNames [
	<generated>
	'FamixPWBQueryFile class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBQueryFile class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FamixPWBQueryFile class >> requirements [

	<generated>
	^ {  }
]
