Class {
	#name : #FamixPWBApplication,
	#superclass : #FamixPWBmajorObject,
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBApplication class >> annotation [

	<MSEClass: #Application super: #FamixPWBmajorObject>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBApplication class >> generatedSlotNames [
	<generated>
	'FamixPWBApplication class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBApplication class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FamixPWBApplication class >> requirements [

	<generated>
	^ {  }
]
