Class {
	#name : #FamixPWBWindow,
	#superclass : #FamixPWBmajorObject,
	#traits : 'FamixTWithInvocations',
	#classTraits : 'FamixTWithInvocations classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBWindow class >> annotation [

	<MSEClass: #Window super: #FamixPWBmajorObject>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBWindow class >> generatedSlotNames [
	<generated>
	'FamixPWBWindow class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBWindow class >> generatedTraitNames [
	<generated>
	^ #(FamixTWithInvocations)
]

{ #category : #meta }
FamixPWBWindow class >> requirements [

	<generated>
	^ {  }
]
