Class {
	#name : #FamixPWBDataWindow,
	#superclass : #FamixPWBSourcedEntity,
	#traits : 'FamixTNamed',
	#classTraits : 'FamixTNamed classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBDataWindow class >> annotation [

	<MSEClass: #DataWindow super: #FamixPWBSourcedEntity>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBDataWindow class >> generatedSlotNames [
	<generated>
	'FamixPWBDataWindow class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBDataWindow class >> generatedTraitNames [
	<generated>
	^ #(FamixTNamed)
]

{ #category : #meta }
FamixPWBDataWindow class >> requirements [

	<generated>
	^ {  }
]
