Class {
	#name : #FamixPWBSourceLanguage,
	#superclass : #FamixPWBEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBSourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixPWBEntity>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]
