Class {
	#name : #FamixPWBMultipleFileAnchor,
	#superclass : #FamixPWBSourceAnchor,
	#traits : 'FamixTMultipleFileAnchor',
	#classTraits : 'FamixTMultipleFileAnchor classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBMultipleFileAnchor class >> annotation [

	<MSEClass: #MultipleFileAnchor super: #FamixPWBSourceAnchor>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBMultipleFileAnchor class >> generatedSlotNames [
	<generated>
	'FamixPWBMultipleFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBMultipleFileAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTMultipleFileAnchor)
]

{ #category : #meta }
FamixPWBMultipleFileAnchor class >> requirements [

	<generated>
	^ {  }
]
