Class {
	#name : #FamixPWBGlobalFunction,
	#superclass : #FamixPWBmajorObject,
	#traits : 'FamixTWithInvocations',
	#classTraits : 'FamixTWithInvocations classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBGlobalFunction class >> annotation [

	<FMClass: #GlobalFunction super: #FamixPWBmajorObject>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]
