Class {
	#name : #FamixPWBIndexedFileAnchor,
	#superclass : #FamixPWBAbstractFileAnchor,
	#traits : 'FamixTIndexedFileNavigation',
	#classTraits : 'FamixTIndexedFileNavigation classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBIndexedFileAnchor class >> annotation [

	<MSEClass: #IndexedFileAnchor super: #FamixPWBAbstractFileAnchor>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBIndexedFileAnchor class >> generatedSlotNames [
	<generated>
	'FamixPWBIndexedFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBIndexedFileAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTIndexedFileNavigation)
]

{ #category : #meta }
FamixPWBIndexedFileAnchor class >> requirements [

	<generated>
	^ {  }
]
