Class {
	#name : #FamixPWBAbstractFileAnchor,
	#superclass : #FamixPWBSourceAnchor,
	#traits : 'FamixTFileAnchor',
	#classTraits : 'FamixTFileAnchor classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBAbstractFileAnchor class >> annotation [

	<MSEClass: #AbstractFileAnchor super: #FamixPWBSourceAnchor>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBAbstractFileAnchor class >> generatedSlotNames [
	<generated>
	'FamixPWBAbstractFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBAbstractFileAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTFileAnchor)
]

{ #category : #meta }
FamixPWBAbstractFileAnchor class >> requirements [

	<generated>
	^ {  }
]
