Class {
	#name : #FamixPWBSourceTextAnchor,
	#superclass : #FamixPWBSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixPWBSourceAnchor>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]
