Class {
	#name : #FamixPWBUnknownSourceLanguage,
	#superclass : #FamixPWBSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixPWBSourceLanguage>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]
