Class {
	#name : #FamixPWBMenuObject,
	#superclass : #FamixPWBmajorObject,
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBMenuObject class >> annotation [

	<MSEClass: #MenuObject super: #FamixPWBmajorObject>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBMenuObject class >> generatedSlotNames [
	<generated>
	'FamixPWBMenuObject class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBMenuObject class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FamixPWBMenuObject class >> requirements [

	<generated>
	^ {  }
]
