Class {
	#name : #FamixPWBWindow,
	#superclass : #FamixPWBmajorObject,
	#traits : 'FamixTWithInvocations',
	#classTraits : 'FamixTWithInvocations classTrait',
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBWindow class >> annotation [

	<FMClass: #Window super: #FamixPWBmajorObject>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #api }
FamixPWBWindow >> incomingReferences [
	^ {}
]
