Class {
	#name : #FamixPWBBasicType,
	#superclass : #FamixPWBAbstractType,
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBBasicType class >> annotation [

	<MSEClass: #BasicType super: #FamixPWBAbstractType>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBBasicType class >> generatedSlotNames [
	<generated>
	'FamixPWBBasicType class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBBasicType class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FamixPWBBasicType class >> requirements [

	<generated>
	^ {  }
]
