Class {
	#name : #FamixPWBStructureFile,
	#superclass : #FamixPWBmajorObject,
	#category : #'Famix-PowerBuilder-Entities-Entities'
}

{ #category : #meta }
FamixPWBStructureFile class >> annotation [

	<MSEClass: #StructureFile super: #FamixPWBmajorObject>
	<package: #'Famix-PowerBuilder-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixPWBStructureFile class >> generatedSlotNames [
	<generated>
	'FamixPWBStructureFile class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixPWBStructureFile class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FamixPWBStructureFile class >> requirements [

	<generated>
	^ {  }
]
