Class {
	#name : #PWBFASTAbstractVisitor,
	#superclass : #Object,
	#category : #'PowerBuilder-Importer-Visitors'
}

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitAccess: aFASTAccess [

]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitCharacterLiteral: aFASTCharacterLiteral [
]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitDottedExpression: aFASTDottedExpression [

]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitEntity: aFASTEntity [
]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitExpression: aFASTExpression [

]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitFloatLiteral: aFASTFloatLiteral [

]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitFunctionInvocation: aFASTFunctionInvocation [

]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitIdentifier: aFASTIdentifier [
]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitImplicitVariable: aFASTImplicitVariable [

]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitIntegerLiteral: aFASTIntegerLiteral [

]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitReturnStatement: aFASTReturnStatement [

]

{ #category : #visiting }
PWBFASTAbstractVisitor >> visitStringLiteral: aFASTStringLiteral [

]
